// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra ir.sadad.config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
/*import { env } from './.env';*/

export const environment = {
  production: true,
  hmr: false,
  version: '0.0.1',
  serverUrl: '',
  defaultLanguage: 'fa-IR',
  supportedLanguages: ['fa-IR', 'en-US'],
  oath: {
    grantType: 'authorization_code',
    redirectUri: 'https://drl.bmi.ir/portal/code',
    clientId: 'dci-ui-client',
    accessTokenUri: 'http://sso:9080/identity/oauth2/auth/token',
    authorizationUri: 'https://my.bmi.ir/identity/oauth2/auth/authorize',
    clientSecret: 'bE1bG3iB4bK4bD1kM2gB5bF1cF1bJ2cE1cC3pD3gL1',
    scope: 'batch-user-info',
  },
  server: {
    inquiryService: '/portal/ir.sadad.services',
    startLaw:
      '<ul>\n    <li>مطالعه و رعایت مفاد نامه های شماره 98/359070 مورخ 1398/10/17 و شماره 98/421492 مورخ 1398/12/05 بانک مرکزی ج.ا.ا ضروری می باشد.</li>\n    <li>تسهیلات اعطایی واحد های تولیدی ریالی که تمام یا بخشی از آن در سال 1397 پرداخت نشده است مشمول قانون مذکور می باشند.</li>\n    <li>اخذ درخواست کتبی از مشتری که در آن به مواردی نظیر تسویه نقدی بدهی-تولیدی بودن- شماره قرارداد/قراردادهای مدنظر مشتری اشاره شود.</li>\n    <li>در صورتی که قرارداد تسهیلات گیرنده با بانک یا موسسه اعتباری تجدید یا امهال نشده باشد. همان قرار داد، ملاک محاسبه مانده بدهی تسهیلات گیرنده بر اساس این قانون خواهد بود.</li>\n    <li>در مورد قراردادهایی که یک یا چند نوبت از طرقی مانند انعقاد توافقنامه، قرارداد جدید یا اعطای تسهیلات جایگزین، تجدید یا امهال شده باشند، اگر قرار داد اولیه قبل از 1393/01/01 منعقد شده باشندآخرین قرارداد و یا توافقنامه قبل از تاریخ مذبور، &laquo;قرارداد ملاک محاسبه&raquo; تلقی می گردد. اگر قرارداد اولیه بعد از 1393/01/01 منعقد شده باشد قرار داد ملاک محاسبه، اولین قرارداد بعد از تاریخ یاد شده می باشد.</li>\n    <li>تصویر و اطلاعات کلیه قراردادها و توافقنامه ها می بایست در سامانه بارگذاری شود.</li>\n    <li>مبنای سقف مجاز، اصل تسهیلات مندرج در &laquo;قرارداد های ملاک محاسبه&raquo; می باشد حقیقی - ۵ میلیارد ریال(۵۰۰ میلیون تومان) و حقوقی- ۲۰ میلیارد ریال (۲میلیارد تومان)</li>\n    <li>بر اساس ماده ۲ دستورالعمل اجرایی قانون تسهیل تسویه بدهی بدهکاران شبکه بانکی کشور ملاک تولیدی/غیر تولیدی بودن اطلاعات ثبت شده در سامانه سمات می باشد.</li>\n    <li>مبالغ پرداختی مشتری بین اجزای بدهی مشتمل بر اصل، سود تا سررسید و سود پس از سررسید تسهیم بالنسبه می گردد.</li>\n    <li>استخراج و ثبت صحیح وصولی های مشتری و هزینه ها بر عهده کاربران می باشد که کاربران ملزم به بارگذاری اسناد وصولی ها و هزینه ها می باشد.</li>\n  </ul>',
  },
};
